on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "jimmyjcl753@gmail.com"
        git config --global user.name "ji-mmyliu"
        git remote set-url origin https://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@github.com/ji-mmyliu/portfolio-website-static.git
        npm run deploy
